name: Build package

on: push

permissions:
  contents: write

jobs:
  build:
    uses: programie/Workflows/.github/workflows/build-minecraft-plugin.yml@main
    secrets: inherit
    with:
      curseforge_id: 438607
      modrinth_id: eT7sT4Kc
      game_versions: '>= 1.20.1'